version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge