"""User repository

Provides database access methods for the User model. The repository
encapsulates common queries used by authentication and user-management
services so higher-level code doesn't need to interact with SQLAlchemy
directly.

Design notes:
 - Methods return model instances (or None) so callers can decide how to
   handle absence (e.g. raise a 404 or return an error response).
 - This repository commits on write operations; for transactional workflows
   consider using an external session or transaction manager.
"""

from sqlalchemy.orm import Session
from models.user_model import User


class UserRepository:
    """Repository for User persistence operations.

    Args:
        db: SQLAlchemy Session instance used for DB operations.
    """

    def __init__(self, db: Session):
        # Store the session; the caller manages session lifecycle
        self.db = db

    def get_all_users(self) -> list[User]:
        """Return a list of all users in the database."""
        return self.db.query(User).all()

    def get_by_email(self, email: str) -> User | None:
        """Find a user by email address.

        Returns None if no user matches the provided email.
        """
        return self.db.query(User).filter(User.email == email).first()

    def get_by_username(self, username: str) -> User | None:
        """Find a user by username.

        Returns None if the username is not found.
        """
        return self.db.query(User).filter(User.username == username).first()

    def get_by_id(self, user_id: int) -> User | None:
        """Retrieve a user by primary key id. Returns None when not found."""
        return self.db.query(User).filter(User.id == user_id).first()

    def create_user(self, username: str, password_hash: str, email: str) -> User:
        """Create and persist a new User.

        Args:
            username: Unique username for the new account.
            password_hash: Pre-hashed password string (do not pass plaintext).
            email: Unique email address for the user.

        Returns:
            The newly created User with generated fields populated (e.g. id).
        """
        new_user = User(
            username=username,
            email=email,
            password_hash=password_hash,
        )
        self.db.add(new_user)
        # Persist the new user immediately; refresh to populate autogenerated fields
        self.db.commit()
        self.db.refresh(new_user)
        return new_user
